# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_kmeans <- function(x, nstart) {
    .Call('CASC_rcpp_kmeans', PACKAGE = 'CASC', x, nstart)
}

